AWSTemplateFormatVersion: '2010-09-09'
Description: 'EKS Version Checker and Upgrade Using Lambda with EventBridge Scheduler'

Parameters:
  NotificationEmail:
    Type: String
    Description: Email address to receive EKS upgrade notifications
  EnableAutoUpgrade:
    Type: String
    AllowedValues: ['true', 'false']
    Default: 'false'
    Description: Enable automatic upgrades for development clusters
  LambdaCodeBucket:
    Type: String
    Description: S3 bucket containing Lambda function code packages
  LambdaCodePrefix:
    Type: String
    Default: 'eks-addon-management/lambda'
    Description: S3 key prefix for Lambda code packages

Resources:
  LambdaExecutionRole:
    Type: AWS::IAM::Role
    Metadata:
      cfn_nag:
        rules_to_suppress:
          - id: W11
            reason: "EKS operations require wildcard resource for list/describe actions"
    DeletionPolicy: Delete
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - !Sub 'arn:${AWS::Partition}:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole'
      Policies:
        - PolicyName: EKSClusterAddonAccess
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - eks:DescribeCluster
                  - eks:ListClusters
                  - eks:DescribeClusterVersions
                  - eks:UpdateClusterVersion
                  - eks:ListInsights
                  - eks:ListAddons
                  - eks:DescribeAddon
                  - eks:DescribeAddonVersions
                  - eks:UpdateAddon
                  - eks:DescribePodIdentityAssociation
                  - eks:UpdatePodIdentityAssociation
                Resource: '*'
              - Effect: Allow
                Action:
                  - sns:Publish
                Resource: !Ref EKSUpgradeNotificationTopic
              - Effect: Allow
                Action:
                  - iam:PassRole
                  - iam:GetRole
                Resource: '*'

  EKSVersionCheckerFunction:
    Type: AWS::Lambda::Function
    Metadata:
      cfn_nag:
        rules_to_suppress:
          - id: CKV_AWS_116
            reason: DLQ not required for scheduled batch processing
          - id: CKV_AWS_173
            reason: No sensitive env vars requiring encryption
          - id: CKV_AWS_117
            reason: VPC not required - communicates only with AWS APIs
          - id: W173
            reason: No sensitive env vars requiring encryption
    DeletionPolicy: Delete
    Properties:
      FunctionName: eks-version-checker
      Runtime: python3.11
      Handler: code.lambda_handler
      Role: !GetAtt LambdaExecutionRole.Arn
      Timeout: 120
      Environment:
        Variables:
          SNS_TOPIC_ARN: !Ref EKSUpgradeNotificationTopic
          ENABLE_AUTO_UPGRADE: !Ref EnableAutoUpgrade
      Code:
        S3Bucket: !Ref LambdaCodeBucket
        S3Key: !Sub '${LambdaCodePrefix}/code.zip'

  SchedulerRole:
    Type: AWS::IAM::Role
    DeletionPolicy: Delete
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: scheduler.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: InvokeLambda
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action: lambda:InvokeFunction
                Resource: !GetAtt EKSVersionCheckerFunction.Arn

  EKSUpgradeNotificationTopic:
    Type: AWS::SNS::Topic
    Metadata:
      cfn_nag:
        rules_to_suppress:
          - id: CKV_AWS_26
            reason: Encryption not required for non-sensitive upgrade notifications
    DeletionPolicy: Delete
    Properties:
      TopicName: eks-upgrade-notifications

  EmailSubscription:
    Type: AWS::SNS::Subscription
    DeletionPolicy: Delete
    Properties:
      Protocol: email
      TopicArn: !Ref EKSUpgradeNotificationTopic
      Endpoint: !Ref NotificationEmail

  WeeklySchedule:
    Type: AWS::Scheduler::Schedule
    DeletionPolicy: Delete
    Properties:
      Name: eks-version-checker-weekly
      ScheduleExpression: 'cron(0 17 ? * FRI *)'
      FlexibleTimeWindow:
        Mode: 'OFF'
      Target:
        Arn: !GetAtt EKSVersionCheckerFunction.Arn
        RoleArn: !GetAtt SchedulerRole.Arn

  # Node Group Management Lambda Resources
  NodeGroupLambdaExecutionRole:
    Type: AWS::IAM::Role
    Metadata:
      cfn_nag:
        rules_to_suppress:
          - id: W11
            reason: "EKS operations require wildcard resource for list/describe actions"
    DeletionPolicy: Delete
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - !Sub 'arn:${AWS::Partition}:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole'
      Policies:
        - PolicyName: EKSNodeGroupAccess
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - eks:DescribeCluster
                  - eks:ListClusters
                  - eks:ListNodegroups
                  - eks:DescribeNodegroup
                  - eks:UpdateNodegroupVersion
                Resource: '*'
              - Effect: Allow
                Action:
                  - sns:Publish
                Resource: !Ref EKSUpgradeNotificationTopic

  NodeGroupManagementFunction:
    Type: AWS::Lambda::Function
    Metadata:
      cfn_nag:
        rules_to_suppress:
          - id: CKV_AWS_116
            reason: DLQ not required for scheduled batch processing
          - id: CKV_AWS_173
            reason: No sensitive env vars requiring encryption
          - id: CKV_AWS_117
            reason: VPC not required - communicates only with AWS APIs
          - id: W173
            reason: No sensitive env vars requiring encryption
    DeletionPolicy: Delete
    Properties:
      FunctionName: eks-nodegroup-version-manager
      Runtime: python3.11
      Handler: nodegroup_code.lambda_handler
      Role: !GetAtt NodeGroupLambdaExecutionRole.Arn
      Timeout: 300
      Environment:
        Variables:
          SNS_TOPIC_ARN: !Ref EKSUpgradeNotificationTopic
          ENABLE_AUTO_UPGRADE: !Ref EnableAutoUpgrade
      Code:
        S3Bucket: !Ref LambdaCodeBucket
        S3Key: !Sub '${LambdaCodePrefix}/nodegroup_code.zip'

  NodeGroupSchedulerRole:
    Type: AWS::IAM::Role
    DeletionPolicy: Delete
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: scheduler.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: InvokeNodeGroupLambda
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action: lambda:InvokeFunction
                Resource: !GetAtt NodeGroupManagementFunction.Arn

  NodeGroupDelayedSchedule:
    Type: AWS::Scheduler::Schedule
    DeletionPolicy: Delete
    Properties:
      Name: eks-nodegroup-manager-weekly
      Description: Triggers node group management 1 hour after addon management
      ScheduleExpression: 'cron(0 18 ? * FRI *)'
      FlexibleTimeWindow:
        Mode: 'OFF'
      Target:
        Arn: !GetAtt NodeGroupManagementFunction.Arn
        RoleArn: !GetAtt NodeGroupSchedulerRole.Arn

Outputs:
  LambdaFunctionArn:
    Description: ARN of the EKS Version Checker Lambda function
    Value: !GetAtt EKSVersionCheckerFunction.Arn
  NodeGroupLambdaFunctionArn:
    Description: ARN of the EKS Node Group Management Lambda function
    Value: !GetAtt NodeGroupManagementFunction.Arn
  ScheduleName:
    Description: Name of the EventBridge Schedule for addon management
    Value: !Ref WeeklySchedule
  NodeGroupScheduleName:
    Description: Name of the EventBridge Schedule for node group management
    Value: !Ref NodeGroupDelayedSchedule
  SNSTopicArn:
    Description: ARN of the SNS notification topic
    Value: !Ref EKSUpgradeNotificationTopic
