AWSTemplateFormatVersion: '2010-09-09'
Description: >-
  Bootstrap infrastructure for EKS Upgrade Automation.
  Creates: S3 bucket for deployment artifacts, GitHub Actions OIDC provider,
  deployer IAM role, and deployer IAM managed policy.
  Deploy this stack ONCE before using the main deploy.yml workflow.

Parameters:
  Environment:
    Type: String
    Default: dev
    AllowedValues: [dev, staging, prod]
    Description: Environment name (used for resource naming and tagging)

  S3BucketName:
    Type: String
    Default: ''
    Description: >-
      Explicit S3 bucket name. Leave blank to auto-generate as
      eks-upgrade-automation-{AccountId}-{Region}

  GitHubOrg:
    Type: String
    Description: GitHub organization or username (e.g., berry2012)

  GitHubRepo:
    Type: String
    Default: automate-eks-upgrades
    Description: GitHub repository name

  CreateOIDCProvider:
    Type: String
    Default: 'true'
    AllowedValues: ['true', 'false']
    Description: >-
      Create GitHub Actions OIDC provider. Set to false if your account
      already has a GitHub OIDC provider registered.

Conditions:
  HasCustomBucketName: !Not [!Equals [!Ref S3BucketName, '']]
  ShouldCreateOIDCProvider: !Equals [!Ref CreateOIDCProvider, 'true']

Resources:
  # ──────────────────────────────────────────────────────────────────
  # S3 Bucket — stores Lambda code packages and CloudFormation templates
  # ──────────────────────────────────────────────────────────────────
  ArtifactBucket:
    Type: AWS::S3::Bucket
    DeletionPolicy: Retain
    UpdateReplacePolicy: Retain
    Properties:
      BucketName: !If
        - HasCustomBucketName
        - !Ref S3BucketName
        - !Sub 'eks-upgrade-automation-${AWS::AccountId}-${AWS::Region}'
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      VersioningConfiguration:
        Status: Enabled
      Tags:
        - Key: Environment
          Value: !Ref Environment
        - Key: Project
          Value: automate-eks-upgrades

  ArtifactBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref ArtifactBucket
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Sid: DenyInsecureTransport
            Effect: Deny
            Principal: '*'
            Action: s3:*
            Resource:
              - !GetAtt ArtifactBucket.Arn
              - !Sub '${ArtifactBucket.Arn}/*'
            Condition:
              Bool:
                aws:SecureTransport: 'false'

  # ──────────────────────────────────────────────────────────────────
  # GitHub Actions OIDC Provider
  # ──────────────────────────────────────────────────────────────────
  GitHubOIDCProvider:
    Type: AWS::IAM::OIDCProvider
    Condition: ShouldCreateOIDCProvider
    Properties:
      Url: https://token.actions.githubusercontent.com
      ClientIdList:
        - sts.amazonaws.com
      ThumbprintList:
        - 6938fd4d98bab03faadb97b34396831e3780aea1
        - 1c58a3a8518e8759bf075b76b750d4f2df264fcd
      Tags:
        - Key: Environment
          Value: !Ref Environment
        - Key: Project
          Value: automate-eks-upgrades

  # ──────────────────────────────────────────────────────────────────
  # Deployer IAM Role — assumed by GitHub Actions via OIDC
  # ──────────────────────────────────────────────────────────────────
  DeployerRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub '${AWS::StackName}-deployer-role'
      Description: Role assumed by GitHub Actions to deploy EKS Upgrade Automation
      MaxSessionDuration: 3600
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Federated: !If
                - ShouldCreateOIDCProvider
                - !GetAtt GitHubOIDCProvider.Arn
                - !Sub 'arn:${AWS::Partition}:iam::${AWS::AccountId}:oidc-provider/token.actions.githubusercontent.com'
            Action: sts:AssumeRoleWithWebIdentity
            Condition:
              StringEquals:
                token.actions.githubusercontent.com:aud: sts.amazonaws.com
              StringLike:
                token.actions.githubusercontent.com:sub: !Sub 'repo:${GitHubOrg}/${GitHubRepo}:*'
      ManagedPolicyArns:
        - !Ref DeployerManagedPolicy
      Tags:
        - Key: Environment
          Value: !Ref Environment
        - Key: Project
          Value: automate-eks-upgrades

  # ──────────────────────────────────────────────────────────────────
  # Deployer Managed Policy — minimum permissions for deployment
  # ──────────────────────────────────────────────────────────────────
  DeployerManagedPolicy:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      ManagedPolicyName: !Sub '${AWS::StackName}-deployer-policy'
      Description: >-
        Permissions required to deploy the EKS Upgrade Automation stack
        via CloudFormation, including Lambda, IAM, SNS, Scheduler, and S3.
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          # CloudFormation stack management
          - Sid: CloudFormation
            Effect: Allow
            Action:
              - cloudformation:CreateStack
              - cloudformation:UpdateStack
              - cloudformation:DeleteStack
              - cloudformation:DescribeStacks
              - cloudformation:DescribeStackEvents
              - cloudformation:DescribeStackResources
              - cloudformation:GetTemplate
              - cloudformation:GetTemplateSummary
              - cloudformation:ValidateTemplate
              - cloudformation:ListStacks
              - cloudformation:CreateChangeSet
              - cloudformation:DescribeChangeSet
              - cloudformation:ExecuteChangeSet
              - cloudformation:DeleteChangeSet
            Resource: '*'

          # S3 — upload Lambda code and CloudFormation templates
          - Sid: S3Artifacts
            Effect: Allow
            Action:
              - s3:PutObject
              - s3:GetObject
              - s3:GetBucketLocation
              - s3:ListBucket
            Resource:
              - !GetAtt ArtifactBucket.Arn
              - !Sub '${ArtifactBucket.Arn}/*'

          # Lambda function management
          - Sid: Lambda
            Effect: Allow
            Action:
              - lambda:CreateFunction
              - lambda:UpdateFunctionCode
              - lambda:UpdateFunctionConfiguration
              - lambda:DeleteFunction
              - lambda:GetFunction
              - lambda:GetFunctionConfiguration
              - lambda:AddPermission
              - lambda:RemovePermission
              - lambda:ListTags
              - lambda:TagResource
              - lambda:UntagResource
              - lambda:PutFunctionConcurrency
              - lambda:DeleteFunctionConcurrency
            Resource:
              - !Sub 'arn:${AWS::Partition}:lambda:${AWS::Region}:${AWS::AccountId}:function:eks-version-checker'
              - !Sub 'arn:${AWS::Partition}:lambda:${AWS::Region}:${AWS::AccountId}:function:eks-nodegroup-version-manager'

          # IAM role and policy management (for Lambda execution roles)
          - Sid: IAMRoles
            Effect: Allow
            Action:
              - iam:CreateRole
              - iam:DeleteRole
              - iam:GetRole
              - iam:UpdateRole
              - iam:PassRole
              - iam:PutRolePolicy
              - iam:GetRolePolicy
              - iam:DeleteRolePolicy
              - iam:AttachRolePolicy
              - iam:DetachRolePolicy
              - iam:ListRolePolicies
              - iam:ListAttachedRolePolicies
              - iam:TagRole
              - iam:UntagRole
            Resource:
              - !Sub 'arn:${AWS::Partition}:iam::${AWS::AccountId}:role/eks-addon-management-*'
              - !Sub 'arn:${AWS::Partition}:iam::${AWS::AccountId}:role/${AWS::StackName}-*'

          # SNS topic management
          - Sid: SNS
            Effect: Allow
            Action:
              - sns:CreateTopic
              - sns:DeleteTopic
              - sns:Subscribe
              - sns:Unsubscribe
              - sns:GetTopicAttributes
              - sns:SetTopicAttributes
              - sns:ListSubscriptionsByTopic
              - sns:TagResource
              - sns:UntagResource
            Resource:
              - !Sub 'arn:${AWS::Partition}:sns:${AWS::Region}:${AWS::AccountId}:eks-upgrade-notifications'

          # EventBridge Scheduler management
          - Sid: Scheduler
            Effect: Allow
            Action:
              - scheduler:CreateSchedule
              - scheduler:UpdateSchedule
              - scheduler:DeleteSchedule
              - scheduler:GetSchedule
              - scheduler:ListSchedules
              - scheduler:TagResource
              - scheduler:UntagResource
            Resource:
              - !Sub 'arn:${AWS::Partition}:scheduler:${AWS::Region}:${AWS::AccountId}:schedule/default/eks-version-checker-weekly'
              - !Sub 'arn:${AWS::Partition}:scheduler:${AWS::Region}:${AWS::AccountId}:schedule/default/eks-nodegroup-manager-weekly'

          # CloudWatch Logs — view Lambda execution logs
          - Sid: CloudWatchLogs
            Effect: Allow
            Action:
              - logs:DescribeLogGroups
              - logs:DescribeLogStreams
              - logs:GetLogEvents
              - logs:FilterLogEvents
            Resource:
              - !Sub 'arn:${AWS::Partition}:logs:${AWS::Region}:${AWS::AccountId}:log-group:/aws/lambda/eks-version-checker:*'
              - !Sub 'arn:${AWS::Partition}:logs:${AWS::Region}:${AWS::AccountId}:log-group:/aws/lambda/eks-nodegroup-version-manager:*'

Outputs:
  ArtifactBucketName:
    Description: S3 bucket name for deployment artifacts (use as S3_BUCKET in deploy workflow)
    Value: !Ref ArtifactBucket
    Export:
      Name: !Sub '${AWS::StackName}-artifact-bucket'

  DeployerRoleArn:
    Description: Deployer IAM role ARN (use as AWS_ROLE_ARN secret in GitHub)
    Value: !GetAtt DeployerRole.Arn
    Export:
      Name: !Sub '${AWS::StackName}-deployer-role-arn'

  DeployerPolicyArn:
    Description: Deployer managed policy ARN
    Value: !Ref DeployerManagedPolicy

  OIDCProviderArn:
    Condition: ShouldCreateOIDCProvider
    Description: GitHub Actions OIDC provider ARN
    Value: !GetAtt GitHubOIDCProvider.Arn
